### ISSUE TITLE
Failed to hook "connect" function of libmysqlclient.21.dylib  On MacOS

### ISSUE THREAD

**Issue by JerryGinger** [kubo/funchook#10]
I  wrote a sample using funchook library to hook "socket/connect" api correctly. When I replaced the basic logic of `socket `and `connect`  with calling api of **libmysqlclient.dylib** , the `socket ` api  hook  takes effect , but `connect ` api hook does not.

**Comment by kubo** [comment]
Could you post the details about "hook does not work" and "in system wide"?
1. Some funchook functions return errors.
2. Hook functions are not called from the process where funchook functions succeed.
3. Hook functions are not called from processes which have not called funchook functions.

If 1, could you send me a debug log generated by `funchook_set_debug_file()`?
If 2, the functions may be inlined. For example `ceil` is a built-in function by default on macOS. When a C compiler detect `ceil`, it generates assembly code there instead of generating a function call to `ceil`.
If 3, it is by design. Funchook doesn't and cannot change the contents of other processes.

**Comment by kubo** [comment]
If you need to check `socket` and `connect` calls to connect to a mysql server, it is better to use [plthook](https://github.com/kubo/plthook).

Funchook replaces the head of `socket` and `connect` with jump instructions. It hooks function calls invoked by any function. So you need to exclude ones unrelated to mysql by yourself.

On the other hand, plthook replaces pointers from a module to another. When `socket` and `connect` entries in libmysqlclient.21.dylib are replaced by plthook, you have no need to exclude unrelated function calls.

**Comment by JerryGinger** [comment]
Thanks for your detailed reply. There was a bug in my code that caused `connect` hook didn't take effect.
