### ISSUE TITLE
Can this project be installed offline？

### ISSUE THREAD

**Issue by lutengda** [kubo/funchook#16]

**Comment by kubo** [comment]
Could you post more explanation?
If you say about compilation, online is required to compile funchook using zydis or capstone disassembler because the disassembler is downloaded on running cmake. Otherwise it doesn't require online. distorm3, which is the default disassembler, is included in [tar.gz or zip packages](https://github.com/kubo/funchook/releases).

**Comment by lutengda** [comment]
> Could you post more explanation?
> If you say about compilation, online is required to compile funchook using zydis or capstone disassembler because the disassembler is downloaded on running cmake. Otherwise it doesn't require online. distorm3, which is the default disassembler, is included in [tar.gz or zip packages](https://github.com/kubo/funchook/releases).

Yes, I am talking about compilation, can those packages that need to be downloaded be put into the project ahead of time, after all, some machines can't surf the Internet

**Comment by lutengda** [comment]
I would also like to ask if this project can be used in unit tests to replace functions that I don't want to call

**Comment by kubo** [comment]
When the target architecture is x86_64 or x86, use the package. No network accesses are required if you don't set `-DFUNCHOOK_DISASM=zydis` or `-DFUNCHOOK_DISASM=capstone` argument to `cmake`.
When the target architecture is arm64(aarch64),  you need to change [here](https://github.com/kubo/funchook/blob/v1.1.0/CMakeLists.txt#L77-L109).

> I would also like to ask if this project can be used in unit tests to replace functions that I don't want to call

Probably.
