### ISSUE TITLE
Example for mac os

### ISSUE THREAD

**Issue by ductus** [kubo/funchook#2]
Hi, can you give me an example for mac os?
I want to change path when open a file: if user open file A, it will display file B.
How can I do that?
Thank you.

**Comment by kubo** [comment]
See [this code](https://github.com/kubo/funchook/blob/4cdeb559b6a4f23cfb562ea88563bd5916aeb76e/test/test_main.c#L207-L305) and use the latest code because old code has [this issue](https://github.com/kubo/funchook/commit/39014699d096bd966f14f51bd009bc2079b640f6).
The code works if your application uses `open()` or `fopen()` to open files.
If your application uses other language, it works only when the language internally calls `open()` or `fopen()` to open files.
