### ISSUE TITLE
Tests fail to build on M1

### ISSUE THREAD

**Issue by drdavella** [kubo/funchook#37]
I ran the following command on my M1 Mac:
```
cmake -B ./build
```

The result was this error:
```
Enabling CAPSTONE_ARM64_SUPPORT
-- Configuring done
CMake Error at test/CMakeLists.txt:33 (add_library):
  Cannot find source file:

    libfunchook_test_arm64_gas.S

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at test/CMakeLists.txt:33 (add_library):
  No SOURCES given to target: funchook_test
```

I am able to work around this by adding `-DFUNCHOOK_BUILD_TESTS=0` to the `cmake` command.

**Comment by kubo** [comment]
This issue itself will be fixed by https://github.com/kubo/funchook/commit/fc73e92fc5b5ee0319995dc2ff7155b96f6a8210.
However I think that funchook doesn't work on M1 mac as noted [here](https://github.com/kubo/funchook#unsupported-platforms).
I believe it is due to [Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime).

**Comment by kaloyan-mm** [comment]
@kubo As we're working and we kind of need to move to M1 - do you think support for M1 is possible?

**Comment by kubo** [comment]
@kaloyan-mm 
I don't think it is possible.
Even if it is possible in a way I don't know now, I cannot check it because I don't have M1 mac.

Who reported that funchook didn't run on M1 mac uses [plthook](https://github.com/kubo/plthook) instead.
