### ISSUE TITLE
Here's another...

### ISSUE THREAD

**Issue by brjoha** [kubo/funchook#5]
https://github.com/coolxv/cpp-stub

**Comment by kubo** [comment]
@brjoha 
Funchook and cpp-stub are same in the point of calling other functions instead of original functions. Both use technique described in [Basic API Hooking section](http://jbremer.org/x86-api-hooking-demystified/#ah-basic). However they are different about calling original functions. Funchook supports [trampoline functions](http://jbremer.org/x86-api-hooking-demystified/#ah-trampoline). On the other hand cpp-stub doesn't.

**Comment by kubo** [comment]
cpp-stub was added to this [List of API Hook Libraries](https://github.com/kubo/funchook/wiki/List-of-API-Hook-Libraries).
